### ISSUE TITLE
Should we add a License to this project?

### ISSUE THREAD

**Issue by Gutierrezjdr** [yizongk/OpenSource-NY#2]
Hi everyone. 
I was thinking since there is no license should be put up a license temporarily and maybe replace it letter? 
What kind of license should we start with?

**Comment by mxmsunny** [comment]
I'm thinking we can use the [MIT license](https://choosealicense.com/licenses/mit/)? It seems like it fits with what we're trying to create.

**Comment by Chocolate-Spaghet** [comment]
On Tuesday we agreed that I’ll be working on License for this project.

**Comment by yizongk** [comment]
Yap, let @Chocolate-Spaghet do it

**Comment by Fioringo** [comment]
Added MIT license
