### ISSUE TITLE
Better file structure

### ISSUE THREAD

**Issue by Fioringo** [yizongk/OpenSource-NY#40]
I think that it would be good to have the client and server side separated. What I mean is have 2 directories (one for server, one for client) and each have their own node modules. That way the modules directories can be modified independently and run independently.

For example:
```
root
+---| server
|   +--- package.json
|   +--- node_modules
|   +--- server.js
|   +--- routes
+---| client
|   +--- package.json
|   +--- node_modules
|   +--- App.js
|   +--- src
|   +--- etc...
```

**Comment by yizongk** [comment]
I like it, I will do it now
